version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña de root
      MYSQL_DATABASE: saludo_db         # Nombre de la base de datos a crear
      MYSQL_USER: user                  # Usuario
      MYSQL_PASSWORD: password          # Contraseña del usuario
    ports:
      - "3306:3306"  # Exponer el puerto de MySQL
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  db_network:
    driver: bridge

volumes:
  db_data:
